package HoBACIoT.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Genre extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Genre() {
    super(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L, 0x6b13425312337c94L, "Genre", "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/7715583511170874516");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Masculin_0 = new EnumerationDescriptor.MemberDescriptor("Masculin", "Masculin", 0x6b13425312337c95L, "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/7715583511170874517");
  private final EnumerationDescriptor.MemberDescriptor myMember_Feminin_0 = new EnumerationDescriptor.MemberDescriptor("Feminin", "Feminin", 0x6b13425312337c96L, "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/7715583511170874518");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L, 0x6b13425312337c94L, 0x6b13425312337c95L, 0x6b13425312337c96L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Masculin_0, myMember_Feminin_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Masculin":
        return myMember_Masculin_0;
      case "Feminin":
        return myMember_Feminin_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
