package HoBACIoT.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MatchID extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MatchID() {
    super(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L, 0x5e7502486e87608fL, "MatchID", "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/6806348921955639439");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_string_0 = new EnumerationDescriptor.MemberDescriptor("string", "string-equal", 0x5e7502486e876090L, "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/6806348921955639440");
  private final EnumerationDescriptor.MemberDescriptor myMember_integer_0 = new EnumerationDescriptor.MemberDescriptor("integer", "string-integer", 0x5e7502486e876091L, "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/6806348921955639441");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L, 0x5e7502486e87608fL, 0x5e7502486e876090L, 0x5e7502486e876091L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_string_0, myMember_integer_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "string":
        return myMember_string_0;
      case "integer":
        return myMember_integer_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
