package HoBACIoT.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Effect extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Effect() {
    super(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L, 0x36d641ea276bdf77L, "Effect", "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/3951418197003722615");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Permit_0 = new EnumerationDescriptor.MemberDescriptor("Permit", "Permit", 0x36d641ea276bdf78L, "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/3951418197003722616");
  private final EnumerationDescriptor.MemberDescriptor myMember_Deny_0 = new EnumerationDescriptor.MemberDescriptor("Deny", "Deny", 0x36d641ea276be1e9L, "r:d3c5e9ba-a836-466a-a7ba-7d798a44fd00(HoBACIoT.structure)/3951418197003723241");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L, 0x36d641ea276bdf77L, 0x36d641ea276bdf78L, 0x36d641ea276be1e9L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Permit_0, myMember_Deny_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Permit":
        return myMember_Permit_0;
      case "Deny":
        return myMember_Deny_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
