package HoBACIoT.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Allumer = 0;
  public static final int Aspirateur = 1;
  public static final int Bluetooth = 2;
  public static final int BrosseDent = 3;
  public static final int Chambre = 4;
  public static final int Cuisine = 5;
  public static final int Enfants = 6;
  public static final int Eteindre = 7;
  public static final int Famille = 8;
  public static final int Four = 9;
  public static final int Frigo = 10;
  public static final int GrandMaman = 11;
  public static final int GrandPapa = 12;
  public static final int GrandParents = 13;
  public static final int Maison = 14;
  public static final int Maman = 15;
  public static final int MicrOnde = 16;
  public static final int Miroir = 17;
  public static final int Papa = 18;
  public static final int Parents = 19;
  public static final int Personne = 20;
  public static final int Piece = 21;
  public static final int Prise = 22;
  public static final int Robinet = 23;
  public static final int SalleDeBain = 24;
  public static final int SalleReunion = 25;
  public static final int Salon = 26;
  public static final int Smart_City = 27;
  public static final int Store = 28;
  public static final int TV = 29;
  public static final int Thermostat = 30;
  public static final int TournerAgauche = 31;
  public static final int TurnerAdroite = 32;
  public static final int Usager = 33;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc51db5c4495f4e00L, 0xb88912a634a9acb3L);
    builder.put(0x653317703a46f0fcL, Allumer);
    builder.put(0x2dc58a2ba3746932L, Aspirateur);
    builder.put(0x2dc58a2ba374692fL, Bluetooth);
    builder.put(0x2dc58a2ba374692bL, BrosseDent);
    builder.put(0x272a6c4fee938e7bL, Chambre);
    builder.put(0x272a6c4fee938e7fL, Cuisine);
    builder.put(0x2dc58a2ba3746901L, Enfants);
    builder.put(0x653317703a46f0feL, Eteindre);
    builder.put(0x2dc58a2ba37468fcL, Famille);
    builder.put(0x2dc58a2ba3746927L, Four);
    builder.put(0x2dc58a2ba3746928L, Frigo);
    builder.put(0x2dc58a2ba3746910L, GrandMaman);
    builder.put(0x2dc58a2ba374690cL, GrandPapa);
    builder.put(0x2dc58a2ba3746900L, GrandParents);
    builder.put(0x272a6c4fee938e8bL, Maison);
    builder.put(0x2dc58a2ba3746909L, Maman);
    builder.put(0x2dc58a2ba3746929L, MicrOnde);
    builder.put(0x2dc58a2ba374692cL, Miroir);
    builder.put(0x2dc58a2ba3746905L, Papa);
    builder.put(0x2dc58a2ba37468ffL, Parents);
    builder.put(0x272a6c4fee938e8cL, Personne);
    builder.put(0x272a6c4fee938e76L, Piece);
    builder.put(0x2dc58a2ba3746931L, Prise);
    builder.put(0x2dc58a2ba374692aL, Robinet);
    builder.put(0x272a6c4fee938e7cL, SalleDeBain);
    builder.put(0x272a6c4fee938e7dL, SalleReunion);
    builder.put(0x272a6c4fee938e7eL, Salon);
    builder.put(0x272a6c4fee938e8aL, Smart_City);
    builder.put(0x2dc58a2ba374692dL, Store);
    builder.put(0x2dc58a2ba3746930L, TV);
    builder.put(0x2dc58a2ba374692eL, Thermostat);
    builder.put(0x653317703a46f0fdL, TournerAgauche);
    builder.put(0x653317703a46f0ffL, TurnerAdroite);
    builder.put(0x4254bfcda6748209L, Usager);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
